drop table if exists "Tours";

create table if not exists "Tours"
(
    "Id" bigint generated by default as identity (start 1 increment 1) primary key,
    "UserId" integer not null,
    "Name" text not null,
    "Description" text not null,
    "Price" double precision not null,
    "Duration" integer,
    "Distance" double precision,
    "Difficulty" integer,
    "TransportType" integer,
    "Status" integer,
    "StatusUpdateTime" timestamp with time zone not null,
    "Tags" text[]
) tablespace pg_default;

alter table "Tours"
    owner to postgres;


insert into "Tours"(
    "UserId", "Name", "Description", "Price", "Duration", "Distance", "Difficulty", "TransportType", "Status", "StatusUpdateTime", "Tags")
VALUES
    (1, 'Zlatibor Nature Escape', 'Discover the natural beauty of Zlatibor.', 1500, 37, 7, 2, 3, 1, '2024-02-16', ARRAY['nature', 'escape', 'Zlatibor']),
    (2, 'Beograd Cultural Delight', 'Immerse yourself in the rich culture of Belgrade.', 1800, 9, 1, 2, 3, 1, '2024-01-26', ARRAY['culture', 'city', 'Belgrade']),
    (3, 'Fruška Gora Monastery Tour', 'Explore the historic monasteries of Fruška gora.', 1200, 10, 5, 2, 3, 1, '2024-03-18', ARRAY['history', 'monastery', 'national park']),
    (4, 'Novi Sad Tour', 'Explore the rich history of the city through its landmarks.', 1500, 60, 6, 2, 3, 1, '2024-01-21', ARRAY['city', 'history', 'culture']),
    (5, 'Fruška gora', 'Take a walkand enjoy the natural beauty of the national park.', 1200, 10, 5, 2, 3, 1, '2024-02-11', ARRAY['mountain', 'national park']),
    (6, 'Ovčar-Kablar Gorge', 'Explore the breathtaking views of Ovčar-Kablar Gorge.', 1800, 32, 8, 2, 3, 1, '2024-02-16', ARRAY['nature', 'adventure']),
    (7, 'Subotica Heritage Tour', 'Discover the architectural wonders of Subotica.', 1600, 32, 8, 2, 3, 1, '2024-01-13', ARRAY['heritage', 'architecture', 'Subotica']),
    (8, 'Kragujevac History Walk', 'Walk through the history of Kragujevac.', 1400, 8, 2, 2, 3, 1, '2024-03-19', ARRAY['history', 'walk', 'Kragujevac']),
    (16, 'Uvac Nature Expedition', 'Experience the stunning nature of Uvac.', 1800, 16, 2, 2, 3, 1, '2024-03-24', ARRAY['nature', 'expedition', 'Uvac']);

drop table if exists "Keypoints";

create table if not exists "Keypoints"
(
    "Id" bigint generated by default as identity (start 1 increment 1) primary key,
    "TourId" integer NOT NULL,
    "Name" text NOT NULL,
    "Latitude" double precision NOT NULL,
    "Longitude" double precision NOT NULL,
    "Description" text,
    "Position" integer,
    "Image" text,
    "Secret" text
) tablespace pg_default;

alter table "Keypoints"
    owner to postgres;

INSERT INTO "Keypoints"(
    "TourId", "Name", "Latitude", "Longitude", "Description", "Position", "Image")
VALUES
    (1, 'Tornik Peak', 43.7451, 19.6609, 'Enjoy the panoramic view from the Tornik peak.', 2, 'https://media.zlatiborapartmani.rs/2020/03/DSC_1615.jpg'),
    (1, 'Zlatibor City Center', 43.7408, 19.7120, 'Start your journey at the heart of Zlatibor.', 1, 'https://kofer.info/wp-content/uploads/2021/08/Jezero-Zlatibor-960x623.jpg'),
    (2, 'Skadarlija Street', 44.8264, 20.4611, 'Experience the bohemian atmosphere of Skadarlija Street.', 2, 'https://www.feelbelgrade.com/en/wp-content/uploads/2014/11/turisti%C4%8Dki-vodi%C4%8D-beograda-skadarlija-apartmani-Beograd.jpg'),
    (2, 'Kalemegdan Fortress', 44.8242, 20.4494, 'Explore the historical Kalemegdan Fortress.', 1, 'https://private-tours.rs/blog/wp-content/uploads/2019/06/apartmani-kod-kalemegdana-1-1024x684.jpg'),
    (3, 'Krušedol Monastery', 45.1114, 19.8918, 'Explore the historic Krušedol Monastery.', 2, 'https://i.pinimg.com/736x/a7/35/03/a735037e8889b17333281b3314656635.jpg'),
    (3, 'Novo Hopovo Monastery', 45.0705, 19.9900, 'Visit the serene Novo Hopovo Monastery.', 1, 'https://novisad.travel/wp-content/uploads/2019/04/DJI_0010_manastir-novo-hopovo-2023_compressed-scaled.jpg'),
    (4, 'Petrovaradin Fortress', 45.2559, 19.8442, 'Visit the iconic square with historical monuments.', 2, 'https://www.srbijanadlanu.rs/wordpress/wp-content/uploads/2020/10/Petrovaradinska-tvrdjava-7a.jpg'),
    (4, 'Novi Sad Center', 45.2671, 19.8335, 'Start your journey at the heart of the city.', 1, 'https://lh3.googleusercontent.com/proxy/CyQ3FD1mxWBO0lyAvhjtUbEQtqPnA_gUwlIX6Gx-MbuCqmpy8M0MhVRxUUy1mJbvOfSEiBkPz3Dnkkoz6KeIUa5IfQ2A4J2LX5ICy4Ax8yMOogP96y1qUNlJ4JLxQakZTKHXt-J4NfzMZJbRMureKw'),
    (5, 'Vrdnik tower', 45.2559, 19.8442, 'Visit the remains of the fortress from the 13th century.', 2, 'https://www.npfruskagora.co.rs/data/images/f54fae881c0d52fdba40e493cf2a39c8_4762932114.jpg'),
    (5, 'A wonderful forest of moss', 45.2671, 19.8335, 'Enjoy beauty of a wonderful forest of moss', 1, 'https://ocdn.eu/images/pulscms/MWI7MDA_/3ccf30ed6b49bb2857a54f4cf640f974.jpg'),
    (6, 'Kablar Viewpoint', 43.9015, 20.2287, 'Enjoy a panoramic view from the Kablar viewpoint.', 2, 'https://www.srbijapodlupom.com/wp-content/uploads/2021/05/IMG-20210531-WA0004.jpg'),
    (6, 'Ovčar Banja Thermal Springs', 43.8872, 20.2234, 'Relax in the natural thermal springs of Ovčar Banja.', 3, 'https://www.wellnesscentar-kablar.com/images/foto-galerija/ovcar-banja/001-ovcar-banja-kanal-zapadne-morave.jpg'),
    (7, 'Sretenje Monastery', 43.8921, 20.2278, 'Visit the historic Sretenje Monastery in Ovčarsko-Kablarska klisura.', 1, 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/bb/Manastir_Sretenje_%28Ov%C4%8Dar%29%2C_zima_23.jpg/1024px-Manastir_Sretenje_%28Ov%C4%8Dar%29%2C_zima_23.jpg'),
    (7, 'Palic Lake Promenade', 46.1063, 19.7601, 'Take a leisurely stroll along the picturesque Palic Lake.', 2, 'https://www.panacomp.net/wp-content/uploads/2016/02/palic-3154.jpg'),
    (8, 'Subotica City Hall', 46.1002, 19.6674, 'Admire the stunning architecture of Subotica City Hall.', 1, 'https://capturingourdays.com/wp-content/uploads/2022/11/art-nouveau-city-hall-in-subotica-1080x720.jpg'),
    (8, 'First Kragujevac Gymnasium', 44.0192, 20.9168, 'Visit the historic First Kragujevac Gymnasium building.', 2, 'https://www.glassumadije.rs/wp-content/uploads/2018/07/Prva-kragujeva%C4%8Dka-gimnazija.jpg'),
    (9, 'National Museum of Kragujevac', 44.0159, 20.9039, 'Explore the rich history at the National Museum of Kragujevac.', 1, 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c7/Wiki_%C5%A0umadija_XVI_National_Museum_of_Kragujevac_854.jpg/640px-Wiki_%C5%A0umadija_XVI_National_Museum_of_Kragujevac_854.jpg'),
    (9, 'Panoramic Viewpoint', 43.5548, 19.8443, 'Enjoy panoramic views from the this viewpoint.', 2, 'https://mayaktours.com/wp-content/uploads/2021/09/zlatibor-uvac-panorama-489618988-scaled.jpg');

