version: "3.9"

services:
  explorer:
    build:
      context: ./old-monolith
      dockerfile: Dockerfile
      target: final
    restart: on-failure
    networks:
      - soa
    ports:
      - "8080:80"
    environment:
      DATABASE_HOST: database
      DATABASE_PORT: 5432
      DATABASE_PASSWORD: super
      DATABASE_USER: postgres
      DATABASE_SCHEMA: explorer
    depends_on:
      - database

  ms-tours:
    build:
      context: ./ms-tours
      dockerfile: Dockerfile
    image: ms_tours_server
    container_name: ms_tours_server
    restart: always
    environment:
      DATABASE_HOST: database
      DATABASE_PORT: 5432
      DATABASE_TYPE: postgresql
      DATABASE_USER: postgres
      DATABASE_SECRET: super
      DATABASE_NAME: tours
    networks:
      - soa
    ports:
      - 7007:7007
    depends_on:
      - database

  ms-encounters:
    build:
      context: ./ms-encounters
      dockerfile: Dockerfile
    image: ms_encounters_server
    container_name: ms_encounters_server
    restart: always
    networks:
      - soa
    ports:
      - 7008:7007
    environment:
      DATABASE_TYPE: postgresql
      DATABASE_USER: postgres
      DATABASE_SECRET: super
      DATABASE_HOST: database
      DATABASE_PORT: 5432
      DATABASE_NAME: encounters
    depends_on:
      - database

  database:
    image: postgres:latest
    restart: always
    networks:
      - soa
    environment:
      POSTGRES_PASSWORD: super
      POSTGRES_USER: postgres
      POSTGRES_MULTIPLE_DATABASES: explorer,encounters,tours
    volumes:
      - ./db_init.sh:/docker-entrypoint-initdb.d/db_init.sh
      - type: bind
        source: ./explorer-init-data.sql
        target: /tmp/explorer-init.sql
    ports:
      - "5432:5432"

  # ms-encounters-database:
  #   image: postgres:13
  #   container_name: ms-encounters-database
  #   restart: always
  #   networks:
  #     - soa
  #   ports:
  #     - 5433:5433
  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: super
  #     POSTGRES_DB: encounters
  #     PGPORT: 5433
  #   volumes:
  #     - database-data:/var/lib/postgresql/data

  # ms-tours-database:
  #   image: postgres:13
  #   container_name: ms-tours-database
  #   restart: always
  #   networks:
  #     - soa
  #   ports:
  #     - 5434:5434
  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: super
  #     POSTGRES_DB: tours
  #     PGPORT: 5434
  #   volumes:
  #     - database-data:/var/lib/postgresql/data

volumes:
  database-data:
    name: explorer

networks:
  soa:
    name: soa
    driver: bridge
