version: "3.9"

services:
  smart-tutor-migration:
    build:
      context: ./old-monolith
      dockerfile: Dockerfile
      target: execute-migration
    networks:
      - soa
    environment:
      DATABASE_HOST: database
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: super
      DATABASE_SCHEMA: explorer
      DATABASE_PORT: 5432

networks:
  soa:
    name: soa
    driver: bridge
    external: true
