version: "3.9"

services:
  explorer:
    build:
      context: ./old-monolith
      dockerfile: Dockerfile
      target: final
    restart: on-failure
    networks:
      - soa
    ports:
      - "8080:80"
    environment:
      DATABASE_HOST: database
      DATABASE_PORT: 5432
      DATABASE_PASSWORD: super
      DATABASE_USER: postgres
      DATABASE_SCHEMA: explorer
    depends_on:
      - database

  ms-tours:
    build:
      context: ./ms-tours
      dockerfile: Dockerfile
    image: ms_tours_server
    container_name: ms_tours_server
    restart: always
    environment:
      DATABASE_HOST: database
      DATABASE_PORT: 5432
      DATABASE_TYPE: postgresql
      DATABASE_USER: postgres
      DATABASE_SECRET: super
      DATABASE_NAME: tours
    networks:
      - soa
    ports:
      - 7007:7007
    depends_on:
      - database

  ms-encounters:
    build:
      context: ./ms-encounters
      dockerfile: Dockerfile
    image: ms_encounters_server
    container_name: ms_encounters_server
    restart: always
    networks:
      - soa
    ports:
      - 7008:7007
    environment:
      DATABASE_TYPE: postgresql
      DATABASE_USER: postgres
      DATABASE_SECRET: super
      DATABASE_HOST: database
      DATABASE_PORT: 5432
      DATABASE_NAME: encounters
    depends_on:
      - database

  ms-followers:
    build:
      context: ./ms-followers
      dockerfile: Dockerfile
    container_name: ms-followers
    restart: always
    networks:
      - soa
    ports:
      - 8000:8000
    depends_on:
      - neo4j-db

  ms-auth:
    build:
      context: ./ms-auth
      dockerfile: Dockerfile
    image: ms_auth_server
    container_name: ms_auth_server
    restart: always
    networks:
      - soa
    ports:
      - 8040:8040
    environment:
      DATABASE_TYPE: postgresql
      DATABASE_USER: postgres
      DATABASE_SECRET: super
      DATABASE_HOST: database
      DATABASE_PORT: 5432
      DATABASE_NAME: users
    depends_on:
      - database

  database:
    image: postgres:latest
    restart: always
    networks:
      - soa
    environment:
      POSTGRES_PASSWORD: super
      POSTGRES_USER: postgres
      POSTGRES_MULTIPLE_DATABASES: explorer,encounters,tours,users
    volumes:
      - ./db_init.sh:/docker-entrypoint-initdb.d/db_init.sh
      - ./old-monolith/scripts/tutours-db-backup.sql:/docker-entrypoint-initdb.d/explorer-init-data.sql
      - ./ms-tours/script/tours.sql:/docker-entrypoint-initdb.d/tours.sql
      - ./ms-encounters/script/encounters.sql:/docker-entrypoint-initdb.d/encounters.sql
      - ./ms-auth/script/users.sql:/docker-entrypoint-initdb.d/users.sql
    ports:
      - "5432:5432"

  neo4j-db:
    image: neo4j
    container_name: neo4j-db
    restart: always
    networks:
      - soa
    ports:
      - 7474:7474
      - 7687:7687
    environment:
      NEO4J_AUTH: neo4j/password
    volumes:
      - /var/lib/neo4j/data:/data

volumes:
  soadb:
    name: explorer

networks:
  soa:
    name: soa
    driver: bridge
