version: "3.9"

services:
  gateway:
    build:
      context: ./gateway
      dockerfile: Dockerfile
    container_name: gateway
    restart: always
    networks:
      - soa
    ports:
      - 8090:8090
    depends_on:
      - monolith-grpc

  monolith-grpc:
    build:
      context: ./old-monolith
      dockerfile: ./grpc/Dockerfile
      target: final
    container_name: monolith-grpc
    restart: on-failure
    networks:
      - soa
    environment:
      DATABASE_HOST: database
      DATABASE_PORT: 5432
      DATABASE_PASSWORD: super
      DATABASE_USER: postgres
      DATABASE_SCHEMA: explorer
    depends_on:
      - database

  database:
    image: postgres:latest
    restart: always
    networks:
      - soa
    environment:
      POSTGRES_PASSWORD: super
      POSTGRES_USER: postgres
      POSTGRES_MULTIPLE_DATABASES: explorer,encounters,tours
    volumes:
      - ./db_init.sh:/docker-entrypoint-initdb.d/db_init.sh
      - ./old-monolith/scripts/tutours-db-backup.sql:/docker-entrypoint-initdb.d/explorer-init-data.sql
      - ./ms-tours/script/tours.sql:/docker-entrypoint-initdb.d/tours.sql
      - ./ms-encounters/script/encounters.sql:/docker-entrypoint-initdb.d/encounters.sql

volumes:
  soadb:
    name: explorer

networks:
  soa:
    name: soa
    driver: bridge
